version: "3.9"
services:
  markov-bot:
    build: .
    container_name: markov-bot
    volumes:
      - /mnt/user/appdata/markov-bot:/app/data
    restart: unless-stopped
    
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}